const $=id=>document.getElementById(id);
const soundFiles={good:'./correct.wav',try:'./try-again.wav'},soundPlayers={};
function playEffect(kind){if(data.soundEffects===false)return;if('audioSession' in navigator)try{navigator.audioSession.type='playback'}catch{}let player=soundPlayers[kind]||(soundPlayers[kind]=new Audio(soundFiles[kind]));player.pause();player.currentTime=0;player.play().catch(()=>{});}
let questions=[],previousKeys=new Set(),at=0,selected=-1,hadMiss=false,solved=false,firstTry=0,streak=0,best=0,perfectAwarded=false,feedback='',feedbackType='';
function start(){questions=grammarRound(grammarConfig(current()),previousKeys);previousKeys=new Set(questions.map(q=>q.key));at=0;selected=-1;hadMiss=false;solved=false;firstTry=0;streak=0;best=current().grammarBestStreak||0;perfectAwarded=false;feedback='';feedbackType='';render()}
function saySentence(q){if(!('speechSynthesis' in window))return;speechSynthesis.cancel();let utterance=new SpeechSynthesisUtterance(q.tokens.map(t=>t.text).join(' ')+'.');utterance.rate=Number(data.speechRate)||.75;let voice=speechSynthesis.getVoices().find(v=>v.name===data.voiceName&&v.lang===data.voiceLang);if(voice)utterance.voice=voice;speechSynthesis.speak(utterance)}
function render(){profiles($('profiles'),start);$('count').textContent=at<questions.length?'Sentence '+(at+1)+' of '+questions.length:'Round complete';$('streak').textContent='🔥 '+streak+' streak';let area=$('exercise');area.replaceChildren();
 if(at>=questions.length){if(!perfectAwarded&&questions.length&&firstTry===questions.length){current().grammarPerfectRounds=(current().grammarPerfectRounds||0)+1;perfectAwarded=true;save()}let end=document.createElement('div');end.className='grammarEnd';end.innerHTML='<div class="big">🏆</div><h2>Wonderful work!</h2><div class="score"></div><p>adjectives found on the first try</p><p class="result"></p>';end.querySelector('.score').textContent=firstTry+' / '+questions.length;end.querySelector('.result').textContent=firstTry===questions.length?'Perfect round! Every adjective found on the first try! ⭐':'Best streak: '+best;let again=document.createElement('button');again.className='primary';again.textContent='New round ↻';again.onclick=start;end.append(again);area.append(end);return}
 let question=questions[at];let prompt=document.createElement('div');prompt.className='grammarPrompt';prompt.innerHTML='<h2>Which word describes something?</h2>';area.append(prompt);let hear=document.createElement('button');hear.className='grammarHear';hear.textContent='🔊 Hear the sentence';hear.onclick=()=>saySentence(question);area.append(hear);
 let sentence=document.createElement('div');sentence.className='sentence';sentence.setAttribute('role','group');sentence.setAttribute('aria-label','Choose the adjective in the sentence');question.tokens.forEach((token,i)=>{let button=document.createElement('button');button.className='wordChoice'+(selected===i?' selected':'')+(solved&&token.part==='adjective'?' correct':'');button.textContent=token.text;button.setAttribute('aria-pressed',String(selected===i));button.disabled=solved;button.onclick=()=>{selected=i;feedback='';feedbackType='';render()};sentence.append(button)});let period=document.createElement('span');period.className='punctuation';period.textContent='.';sentence.append(period);area.append(sentence);
 let tip=document.createElement('p');tip.className='grammarHint';tip.textContent='Tap one word, then check your answer.';area.append(tip);let check=document.createElement('button');check.className='primary grammarCheck';check.textContent=solved?'Next sentence →':'Check answer';check.onclick=()=>{if(solved){at++;selected=-1;hadMiss=false;solved=false;feedback='';feedbackType='';render();return}if(selected<0){feedback='Choose a word first.';feedbackType='try';render();return}if(question.tokens[selected].part==='adjective'){if(!hadMiss){firstTry++;streak++;best=Math.max(best,streak);current().grammarBestStreak=best;save()}solved=true;feedback=hadMiss?'You found it! 🌼':streak>=3?streak+' in a row! ⭐':'That’s right! 🎉';feedbackType='good';playEffect('good')}else{hadMiss=true;streak=0;feedback='Not quite. Try a word that describes the '+question.tokens.find(t=>t.part==='noun').text+'.';feedbackType='try';playEffect('try')}render()};area.append(check);
 let msg=document.createElement('p');msg.className='grammarFeedback '+feedbackType;msg.setAttribute('role','status');msg.textContent=feedback;area.append(msg);let track=document.createElement('div');track.className='grammarProgress';let fill=document.createElement('span');fill.style.width=(at/questions.length*100)+'%';track.append(fill);area.append(track)}
start();
