const $=id=>document.getElementById(id);
const soundFiles={good:'./correct.wav',try:'./try-again.wav'},soundPlayers={};
function playEffect(kind){if(data.soundEffects===false)return;if('audioSession' in navigator)try{navigator.audioSession.type='playback'}catch{}let player=soundPlayers[kind]||(soundPlayers[kind]=new Audio(soundFiles[kind]));player.pause();player.currentTime=0;player.play().catch(()=>{});}
let activePart=null,questions=[],previousByPart={},at=0,selected=-1,hadMiss=false,solved=false,firstTry=0,streak=0,best=0,perfectAwarded=false,feedback='',feedbackType='';
function start(part=activePart){activePart=part;let config={...grammarConfig(current()),part};questions=grammarRound(config,previousByPart[part]||new Set());previousByPart[part]=new Set(questions.map(q=>q.key));at=0;selected=-1;hadMiss=false;solved=false;firstTry=0;streak=0;best=current().grammarCourses?.[part]?.bestStreak||0;perfectAwarded=false;feedback='';feedbackType='';render()}
function saySentence(q){if(!('speechSynthesis' in window))return;speechSynthesis.cancel();let utterance=new SpeechSynthesisUtterance(q.tokens.map(t=>t.text).join(' ')+'.');utterance.rate=Number(current().speechRate??data.speechRate??.75);let voice=speechSynthesis.getVoices().find(v=>v.name===(current().voiceName??data.voiceName)&&v.lang===(current().voiceLang??data.voiceLang));if(voice)utterance.voice=voice;speechSynthesis.speak(utterance)}
function showCourses(){activePart=null;questions=[];render()}
function render(){let part=activePart;$('activityTitle').textContent=part?'Find the '+part+'!':'Choose what to find!';$('activityHelp').textContent=part==='noun'?'A noun names a person, place, or thing. Tap the noun in each sentence.':part==='verb'?'A verb shows an action. Tap the action word in each sentence.':part==='adjective'?'An adjective describes a person, place, or thing. Tap the describing word in each sentence.':'Pick a course to start a new round.';profiles($('profiles'),()=>{previousByPart={};showCourses()});$('courseBack').hidden=!part;$('courseBack').style.display=part?'inline-block':'none';$('courseBack').onclick=showCourses;$('roundBar').hidden=!part;$('roundBar').style.display=part?'flex':'none';let area=$('exercise');area.replaceChildren();if(!part){let courses=document.createElement('div');courses.className='grammarCourses';for(let [type,icon,title,clue] of [['noun','🧩','Nouns','Find who or what the sentence is about'],['verb','🏃','Verbs','Find the action word'],['adjective','🎨','Adjectives','Find the describing word']]){let button=document.createElement('button');button.className='grammarCourse';button.innerHTML='<span class="courseIcon"></span><strong></strong><small></small>';button.querySelector('.courseIcon').textContent=icon;button.querySelector('strong').textContent=title;button.querySelector('small').textContent=clue;button.onclick=()=>start(type);courses.append(button)}area.append(courses);return}$('count').textContent=at<questions.length?'Sentence '+(at+1)+' of '+questions.length:'Round complete';$('streak').textContent='🔥 '+streak+' streak';
 if(at>=questions.length){if(!perfectAwarded&&questions.length&&firstTry===questions.length){current().grammarPerfectRounds=(current().grammarPerfectRounds||0)+1;let scores=current().grammarCourses||(current().grammarCourses={});let entry=scores[part]||(scores[part]={});entry.perfectRounds=(entry.perfectRounds||0)+1;perfectAwarded=true;save()}let end=document.createElement('div');end.className='grammarEnd';end.innerHTML='<div class="big">🏆</div><h2>Wonderful work!</h2><div class="score"></div><p class="scoreLabel"></p><p class="result"></p>';end.querySelector('.scoreLabel').textContent=part+'s found on the first try';end.querySelector('.score').textContent=firstTry+' / '+questions.length;end.querySelector('.result').textContent=firstTry===questions.length?'Perfect round! Every '+part+' found on the first try! ⭐':'Best streak: '+best;let again=document.createElement('button');again.className='primary';again.textContent='New round ↻';again.onclick=()=>start(part);end.append(again);area.append(end);return}
 let question=questions[at];let prompt=document.createElement('div');prompt.className='grammarPrompt';prompt.innerHTML='<h2></h2>';prompt.querySelector('h2').textContent=part==='adjective'?'Which word describes something?':part==='noun'?'Which word names a person, place, or thing?':'Which word shows an action?';area.append(prompt);let hear=document.createElement('button');hear.className='grammarHear';hear.textContent='🔊 Hear the sentence';hear.onclick=()=>saySentence(question);area.append(hear);
 let sentence=document.createElement('div');sentence.className='sentence';sentence.setAttribute('role','group');sentence.setAttribute('aria-label','Choose the '+part+' in the sentence');question.tokens.forEach((token,i)=>{let button=document.createElement('button');button.className='wordChoice'+(selected===i?' selected':'')+(solved&&token.part===part?' correct':'');button.textContent=token.text;button.setAttribute('aria-pressed',String(selected===i));button.disabled=solved;button.onclick=()=>{selected=i;feedback='';feedbackType='';render()};sentence.append(button)});let period=document.createElement('span');period.className='punctuation';period.textContent='.';sentence.append(period);area.append(sentence);
 let tip=document.createElement('p');tip.className='grammarHint';tip.textContent='Tap one word, then check your answer.';area.append(tip);let check=document.createElement('button');check.className='primary grammarCheck';check.textContent=solved?'Next sentence →':'Check answer';check.onclick=()=>{if(solved){at++;selected=-1;hadMiss=false;solved=false;feedback='';feedbackType='';render();return}if(selected<0){feedback='Choose a word first.';feedbackType='try';render();return}if(question.tokens[selected].part===part){if(!hadMiss){firstTry++;streak++;best=Math.max(best,streak);let scores=current().grammarCourses||(current().grammarCourses={});let entry=scores[part]||(scores[part]={});entry.bestStreak=best;current().grammarBestStreak=Math.max(current().grammarBestStreak||0,best);save()}solved=true;feedback=hadMiss?'You found it! 🌼':streak>=3?streak+' in a row! ⭐':'That’s right! 🎉';feedbackType='good';playEffect('good')}else{hadMiss=true;streak=0;feedback=part==='adjective'?'Not quite. Try a word that describes the '+question.tokens.find(t=>t.part==='noun').text+'.':part==='noun'?'Not quite. Find who or what the sentence is about.':'Not quite. Find what the '+question.tokens.find(t=>t.part==='noun').text+' does.';feedbackType='try';playEffect('try')}render()};area.append(check);
 let msg=document.createElement('p');msg.className='grammarFeedback '+feedbackType;msg.setAttribute('role','status');msg.textContent=feedback;area.append(msg);let track=document.createElement('div');track.className='grammarProgress';let fill=document.createElement('span');fill.style.width=(at/questions.length*100)+'%';track.append(fill);area.append(track)}
render();
