const soundFiles={good:'./correct.wav',try:'./try-again.wav'},soundPlayers={};
function playEffect(kind){if(data.soundEffects===false)return;if('audioSession' in navigator)try{navigator.audioSession.type='playback'}catch{}let player=soundPlayers[kind]||(soundPlayers[kind]=new Audio(soundFiles[kind]));player.pause();player.currentTime=0;player.play().catch(()=>{});}
let questions=[],at=0,input='',streak=0,best=0,firstTry=0,missed={},hadMiss=false,feedback='',feedbackType='',solved=false,perfectAwarded=false,previousKeys=new Set();
const $=id=>document.getElementById(id);
function start(){let c=mathConfig(current());questions=generateRound(c,previousKeys);previousKeys=new Set(questions.map(q=>q.key));at=0;input='';streak=0;best=current().mathBestStreak||0;firstTry=0;missed={};hadMiss=false;feedback='';feedbackType='';solved=false;perfectAwarded=false;render()}
function expression(q){let parts=[q.a,symbols[q.op],q.b,'=',q.result];parts[q.blank*2]='<span class="blank">'+(input||'&nbsp;')+'</span>';return parts.join(' ')}
function render(){profiles($('profiles'),start);let area=$('exercise');area.replaceChildren();$('count').textContent=at<questions.length?'Problem '+(at+1)+' of '+questions.length:'Round complete';$('streak').textContent='🔥 '+streak+' streak';if(at>=questions.length){if(!perfectAwarded&&questions.length&&firstTry===questions.length){current().mathPerfectRounds=(current().mathPerfectRounds||0)+1;perfectAwarded=true;save()}let end=document.createElement('div');end.className='roundEnd';let weak=Object.entries(missed).filter(([,n])=>n>0).map(([op,n])=>symbols[op]+' '+n).join(' · ');end.innerHTML='<div class="big">🏆</div><h2>Wonderful work!</h2><div class="score"></div><p>correct on the first try</p><div class="stat"></div><div class="stat"></div>';end.querySelector('.score').textContent=firstTry+' / '+questions.length;let stats=end.querySelectorAll('.stat');stats[0].textContent='Best streak: '+best;stats[1].textContent=weak?'A little more practice: '+weak:'Every problem right on the first try! ⭐';let again=document.createElement('button');again.className='primary';again.textContent='New round ↻';again.onclick=start;end.append(again);area.append(end);return}
 let q=questions[at],equation=document.createElement('div');equation.className='equation';equation.innerHTML=expression(q);equation.setAttribute('aria-label',`Problem ${at+1}: ${q.blank===0?'blank':q.a} ${symbols[q.op]} ${q.blank===1?'blank':q.b} equals ${q.blank===2?'blank':q.result}`);area.append(equation);
 let tip=document.createElement('p');tip.className='muted';tip.textContent='Tap the numbers below to fill the blank.';area.append(tip);let keypad=document.createElement('div');keypad.className='keypad';for(let digit of ['1','2','3','4','5','6','7','8','9','Clear','0','⌫']){let button=document.createElement('button');button.className='key'+(isNaN(Number(digit))||digit==='⌫'?' alt':'');button.textContent=digit;button.disabled=solved;button.setAttribute('aria-label',digit==='⌫'?'Backspace':digit);button.onclick=()=>{if(digit==='Clear')input='';else if(digit==='⌫')input=input.slice(0,-1);else if(input.length<3)input+=digit;feedback='';feedbackType='';render()};keypad.append(button)}area.append(keypad);
 let check=document.createElement('button');check.className='primary check';check.textContent=solved?'Next problem →':'Check answer';check.onclick=()=>{if(solved){at++;input='';hadMiss=false;solved=false;feedback='';feedbackType='';render();return}if(input===''){feedback='Put a number in the blank first.';feedbackType='try';render();return}if(Number(input)===q.answer){if(!hadMiss){firstTry++;streak++;best=Math.max(best,streak);current().mathBestStreak=best;save()}playEffect('good');feedback=hadMiss?'You got it! Keep going 🌼':streak>=3?streak+' in a row! ⭐':'That’s right! Great job! 🎉';feedbackType='good';solved=true}else{if(!hadMiss){missed[q.op]=(missed[q.op]||0)+1;hadMiss=true}streak=0;playEffect('try');feedback='Not quite. Try again!';feedbackType='try';input=''}render()};area.append(check);
 let msg=document.createElement('p');msg.className='feedback '+feedbackType;msg.setAttribute('role','status');msg.textContent=feedback;area.append(msg);let progress=document.createElement('div');progress.className='progress';let bar=document.createElement('span');bar.style.width=(at/questions.length*100)+'%';progress.append(bar);area.append(progress)}
start();
